# Generated by Django 5.0.3 on 2024-03-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='WanderlustUser',
        ),
    ]
