# Generated by Django 5.0.3 on 2024-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0002_rename_customuser_wanderlustuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanderlustuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
