# Generated by Django 5.0.3 on 2024-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0003_alter_wanderlustuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanderlustuser',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
