# Generated by Django 5.0.3 on 2024-03-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0004_wanderlustuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanderlustuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
