# Generated by Django 5.0.3 on 2024-03-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0005_alter_wanderlustuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=255)),
                ('travel_mode', models.CharField(choices=[('AIRPLANE', 'Airplane'), ('CAR', 'Car'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('OTHER', 'Other')], max_length=50)),
                ('accommodation_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('AIRBNB', 'Airbnb'), ('CAMPSITE', 'Campsite'), ('OTHER', 'Other')], max_length=50)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
