# Generated by Django 5.0.3 on 2024-03-30 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0006_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('AIRPLANE', 'Airplane'), ('CAR', 'Car'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('CRUISE', 'Cruise'), ('WALK', 'Walk'), ('MIXED', 'Mixed')], max_length=50),
        ),
    ]
