# Generated by Django 5.0.3 on 2024-03-31 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0007_trip_max_participants_trip_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='notes',
        ),
    ]
