# Generated by Django 5.0.3 on 2024-03-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0008_remove_trip_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('AIRPLANE', 'Airplane'), ('CAR', 'Car'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('CRUISE', 'Cruise'), ('WALK', 'Walk'), ('MULTIPLE', 'Multiple')], max_length=50),
        ),
    ]
