# Generated by Django 5.0.3 on 2024-03-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0009_alter_trip_travel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
    ]
