# Generated by Django 5.0.3 on 2024-03-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0010_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(max_length=50),
        ),
    ]
