# Generated by Django 5.0.3 on 2024-03-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wanderlust', '0011_alter_trip_accommodation_type_alter_trip_travel_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='accommodation_type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('HOSTEL', 'Hostel'), ('AIRBNB', 'Airbnb'), ('CAMPSITE', 'Campsite'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('AIRPLANE', 'Airplane'), ('CAR', 'Car'), ('TRAIN', 'Train'), ('BUS', 'Bus'), ('CRUISE', 'Cruise'), ('WALK', 'Walk'), ('MULTIPLE', 'Multiple')], max_length=50),
        ),
    ]
